package dev.clares.chatgames.game;
public enum GameType { MATH, TRIVIA, REACTION, RANDOM, UNREVERSE, UNSCRAMBLE, VARIABLE, FILLOUT, CLICKABLE, HOVERABLE, GUESS_THE_NUMBER, HUNT, MINE, PLACE, FISH, EAT, CRAFT, FURNACE, UNKNOWN }
